name: Build ARM64 and AMD64 binaries.

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: ~

jobs:
  ARM64:
    name: Build ARM64 binary (Until GitHub adds public ARM64 runs on IDCT-DRAGON).
    runs-on: [self-hosted, linux, ARM64]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build builder
        run: docker build -t rabbit-going-nats/builder --platform linux/arm64 builder/

      - name: Build ARM64 binary
        run: docker run --rm -w /app -v ./:/app --platform linux/arm64 rabbit-going-nats/builder dotnet publish

      - name: Prepare test
        run: ./setup-test.sh

      - name: Run app in the background
        run: nohup bin/Release/net8.0/linux-arm64/publish/RabbitGoingNats &

      - name: Run test
        run: ./run-test.sh

      - name: Store ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: arm64-binary
          path: bin/Release/net8.0/linux-arm64/publish/
          compression-level: 9 # maximum compression

  AMD64:
    name: Build AMD binary.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build builder
        run: docker build -t rabbit-going-nats/builder --platform linux/amd64 builder/

      - name: Build AMD64 binary
        run: docker run --rm -w /app -v ./:/app --platform linux/amd64 rabbit-going-nats/builder dotnet publish

      - name: Prepare test
        run: ./setup-test.sh

      - name: Run app in the background
        run: nohup bin/Release/net8.0/linux-x64/publish/RabbitGoingNats &

      - name: Run test
        run: ./run-test.sh

      - name: Store AMD64 binary
        uses: actions/upload-artifact@v4
        with:
          name: amd64-binary
          path: bin/Release/net8.0/linux-x64/publish/
          compression-level: 9 # maximum compression